[package]
name = "read_csv"
version = "0.1.1"
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
csv = "1.1"
polars = "0.35.4"  # Update to the latest available version
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108" 
 

